services:
  broker:
    container_name: bard-broker
    image: "ghcr.io/pda-aswe/broker:latest"
    ports:
      - "1883:1883"
    restart: on-failure
  casepreis:
    container_name: bard-casepreis
    depends_on:
      - broker
      - servicepreis
      - servicekalender
      - servicemail
    image: "ghcr.io/pda-aswe/casepreis"
    restart: on-failure
  casesport:
    container_name: bard-casesport
    depends_on:
      - broker
      - servicekalender
      - servicesport
      - servicewetter
    image: "ghcr.io/pda-aswe/casesport"
    restart: on-failure
  casenews:
    container_name: bard-casenews
    depends_on:
      - broker
      - servicelocation
      - servicenews
    image: "ghcr.io/pda-aswe/casenews"
    restart: on-failure
  casewelcome:
    container_name: bard-casewelcome
    depends_on:
      - broker
      - servicekalender
      - servicewetter
      - serviceverkehrsinfos
    image: "ghcr.io/pda-aswe/casewelcome"
    restart: on-failure
  casekalender:
    container_name: bard-casekalender
    depends_on:
      - broker
      - servicekalender
    image: "ghcr.io/pda-aswe/casekalender"
    restart: on-failure
  servicewetter:
    container_name: bard-servicewetter
    depends_on:
      - broker
      - servicelocation
    image: "ghcr.io/pda-aswe/servicewetter"
    volumes:
      - ./credentials/openWeatherMap.txt:/app/key.txt
    restart: on-failure
  serviceverkehrsinfos:
    container_name: bard-serviceverkehrsinfos
    depends_on:
      - broker
      - servicelocation
    image: "ghcr.io/pda-aswe/serviceverkehrsinfos"
    volumes:
      - ./credentials/mapquest.txt:/app/key.txt
    restart: on-failure
  servicekalender:
    container_name: bard-servicekalender
    depends_on:
      - broker
    image: "ghcr.io/pda-aswe/servicekalender"
    volumes:
      - ./credentials/token.json:/app/token.json
    restart: on-failure
  servicenews:
    container_name: bard-servicenews
    depends_on:
      - broker
    image: "ghcr.io/pda-aswe/servicenews"
    restart: on-failure
  servicelocation:
    container_name: bard-servicelocation
    depends_on:
      - broker
    image: "ghcr.io/pda-aswe/servicelocation"
    restart: on-failure
  servicesport:
    container_name: bard-servicesport
    depends_on:
      - broker
    image: "ghcr.io/pda-aswe/servicesport"
    restart: on-failure
  servicepreis:
    container_name: bard-servicepreis
    depends_on:
      - broker
    image: "ghcr.io/pda-aswe/servicepreis"
    volumes:
      - ./credentials/finnhub.txt:/app/key.txt
    restart: on-failure
  servicemail:
    container_name: bard-servicemail
    depends_on:
      - broker
    image: "ghcr.io/pda-aswe/servicemail"
    volumes:
      - ./credentials/token.json:/app/token.json
    restart: on-failure
